// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `ButtonComponent.ts` by running `npm run gen:components`.
import type { IClickable, IRightClickable } from '../fake-dom-stuff/ButtonComponent';

export function CastToClickable(obj: any): IClickable | null {
  return (obj !== null && obj !== undefined && typeof(obj.onClick) === "function") ? obj : null;
}

export function CastToRightClickable(obj: any): IRightClickable | null {
  return (obj !== null && obj !== undefined && typeof(obj.onRightClick) === "function") ? obj : null;
}
