// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `HTMLElementWithCustomComponent.ts` by running `npm run gen:components`.
import type { HTMLElementWithCustomComponent } from '../fake-dom-stuff/HTMLElementWithCustomComponent';

export function CastToTMLElementWithCustomComponent(obj: any): HTMLElementWithCustomComponent | null {
  return (obj !== null && obj !== undefined && CastToTMLElement(obj) !== null && CastToTMLElement(obj) !== null) ? obj : null;
}
