import type { IAdvancedGrabber, IBlergh, IGrabbable, IGrabber } from './interfaces';

// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `interfaces.ts` by running `npm run gen:components`.


const Cast = {
  toGrabbable: function (obj: any): IGrabbable | null {
    return (obj.GetNumber !== undefined && obj.GetThing !== undefined) ? obj : null;
  },
  toGrabber: function (obj: any): IGrabber | null {
    return (obj.DoThing !== undefined && obj.speed !== undefined) ? obj : null;
  },
  toAdvancedGrabber: function (obj: any): IAdvancedGrabber | null {
    return (Cast.toGrabbable(obj) && obj.OtherThing !== undefined) ? obj : null;
  },
  toBlergh: function (obj: any): IBlergh | null {
    return (obj.GetAAAAAAAAAAAHHHHThing !== undefined) ? obj : null;
  },
};


export default Cast;