// This is an autogenerated file, DO NOT EDIT.
// This file was generated from `MainScene.ts` by running `npm run gen:components`.
import type { IMario } from '../scenes/MainScene';

export function CastMario(obj: any): IMario | null {
  return (typeof(obj.GetNumber) === "function" && typeof(obj.GetThing) === "function" && typeof(obj.DoMarioThing) === "function") ? obj : null;
}
